### ISSUE TITLE
Including more regions

### ISSUE THREAD

**Issue by gorgobacka** [ckrey/stressmap#6]
I'm collecting incidents for my city for a while now with the Simra Android app.

It would be great, if Leipzig can be included.

I'm also wondering, if it would be possible to create a map for all recorded incidents. Not only based on specific regions. (I haven't looked in the code yet.) However, that is only useful, if the data is widespread.

**Comment by ckrey** [comment]
I included Leipzig and Halle into this Bicycle Infrastructure Quality Map based on OSM data

This map is not integrated with Simra data. Please contact the Simra team https://www.digital-future.berlin/en/research/projects/simra/

**Comment by gorgobacka** [comment]
Thanks.

Oh, I thought it's integrated. I should read the direction more carefully.

But that's anyway for updating the regions. It's a great source.
